### ISSUE TITLE
How to get response code returned by APNS?

### ISSUE THREAD

**Issue by amakkar** [relayrides/pushy#336] opened 2016-07-04 12:59 UTC
Hi,

Is there any way to get the response status code returned by APNS like those mentioned in table 6-4 on this link - 
https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH101-SW18

Thanks,
Akash

**Comment by jchambers** [comment] 2016-07-04 14:59
No (though can get the "reason" from Table 6-6 using [`PusnNotificationResponse#getRejectionReason`](http://relayrides.github.io/pushy/apidocs/0.7/com/relayrides/pushy/apns/PushNotificationResponse.html). Do you have a use case where you need the HTTP response code?

**Comment by amakkar** [comment] 2016-07-05 05:10
Yes, in case of response code 50x, I want to retry that notification after certain interval. 
Also for MIS purpose, management wants to know status of each notification whether it is 200 or 40x or 50x. 
I am also sending notifications to android and windows devices, so the common way to check status is by HTTP response code.

Thanks,
Akash

**Comment by jchambers** [comment] 2016-07-05 14:07
That makes sense. Rather than exposing the status code, though, I wonder if it would make more sense to report an HTTP/500 as a write failure (i.e. mark the `Future` from `sendNotification` as "failed") rather than a rejected notification. As long as the `Future` fails with a predictable exception (maybe introduce a new `InternalServerErrorException`?), I think that would mean:

1. You can retry notifications that get an HTTP/500 just like any other write failure.
2. Because we're using a predictable exception, you can still differentiate between 200 (accepted), 4xx (rejected), and 500 (unknown error) for reporting purposes.
3. We're not really introducing any new complexity, since this all happens through existing channels.

What do you think?

**Comment by amakkar** [comment] 2016-07-07 10:30
I agree with you but is it possible this way - 

1. Add new primitive variable in class SimplePushNotificationResponse called statusCode.
2. The point at where response is parsed (in method onDataRead in class ApnsClientHandlerFrameAdapter) get the HTTP status code from headers and create new SimplePushNotificationResponse - 

`new SimplePushNotificationResponse<>(
                        pushNotification, success, errorResponse.getReason(), errorResponse.getTimestamp(), statusCode)`

Well to be frank with you, I don't whether the above solution will work or not in all cases. 
Please suggest.

Thanks,
Akash

**Comment by jchambers** [comment] 2016-07-07 14:15
Yes, that's possible.

I'd still prefer not to reveal actual status codes if we can avoid it, though. My concern is that status codes are mostly an under-the-hood implementation detail, and exposing them publicly introduces complexity that doesn't come with any fundamentally new capabilities. Put differently, if we treat all 200s as "accepted" notifications (which is already the case), 400s as "rejected" notifications (which is already the case), and 500s as write failures (for which we'd have to make some very modest changes), then I don't think there's any new action users could really take knowing which specific status code was associated with a response.

Does that make sense?

**Comment by amakkar** [comment] 2016-07-07 17:04
Well that makes sense. Let's do it this way then.
Just one question, what if APNS starts to return some other response code in future? Will that be handled or the modification in code will be required?

**Comment by jchambers** [comment] 2016-07-07 17:17
> what if APNS starts to return some other response code in future?

I guess it depends on what the new thing is. Generally, if the status codes demand new behavior, the expectation is that we'll update Pushy accordingly. We're certainly expecting some new status codes to come with token authentication (see #314), for example. One of them is "signing key expired," in which case Pushy will generate a new key and try to send the notification again.

**Comment by amakkar** [comment] 2016-07-07 17:21
Ok, it makes sense. So will you make the code changes for this support or tell me how to proceed?

**Comment by jchambers** [comment] 2016-07-07 17:48
We'll do it.

**Comment by jchambers** [comment] 2016-07-08 23:26
A pull request to treat internal server errors as temporarily failures is open at #337.

**Comment by jchambers** [comment] 2016-07-09 20:34
#337 has been merged.

**Closed by jchambers** 2016-07-09 20:34 UTC
Labels: enhancement

**Comment by amakkar** [comment] 2016-07-11 08:32
Hi Jon,

Thanks for the work done. Can you help me with - 

1. how to build the project. If possible provide the maven dependency for the same.
2. at what point in code should the new Server Exception thrown be handled.

**Comment by jchambers** [comment] 2016-07-11 14:07
> how to build the project.

Same as any other Maven project. `mvn package` or `mvn install` should do the job, depending on your needs. If you need help with Maven in general, please consider asking on [the mailing list](https://groups.google.com/d/forum/pushy-apns).

> at what point in code should the new Server Exception thrown be handled.

That's up to you. It will be the cause of a failed future when sending notifications, though. Please see the [new unit tests](https://github.com/relayrides/pushy/pull/337/files#diff-13765c0845d87266dec0a0f1e182075fR694) for an example.
