### ISSUE TITLE
metricsListener notificationAccepted handler is called on ExpiredProviderToken rejection

### ISSUE THREAD

**Issue by jpermar** [relayrides/pushy#448] opened 2017-04-13 23:53 UTC
It appears that Pushy metricsListener notificationAccepted handler is called when a push to Apns response has rejectionReason=ExpiredProviderToken. Here is what I see:

1) send a notification through Pushy

2) ApnsClient debug messages report two notifications sent: one with response "success=false, rejectionReason=ExpiredProviderToken" and second with "success=true, rejectionReason=null".

3) the notification sent handler is called twice, as expected in this case due to the internal Pushy retry, but the notificationAccepted handler is also called twice, even though only one response was "success=true".

**Comment by jchambers** [comment] 2017-05-07 03:30
@jpermar I'm having a hard time reproducing this. I added tests in 186240d, but they all pass. I think this may mean that we fixed the problem incidentally in #451, which untangled some token-handling logic.

I'm going to close this for now (since I think the problem is solved), but please do leave a comment if you feel that something more is required.

**Comment by jchambers** [comment] 2017-05-07 03:35
Looks like I spoke too soon. The [tests do fail](https://travis-ci.org/relayrides/pushy/jobs/229587531), but only sometimes. I think that means we have a race condition somewhere. Will continue to investigate.

**Comment by jchambers** [comment] 2017-05-07 18:24
Looks like the problem was with the tests and not the underlying client code. I think everything is under control as of 49f45e1. Thanks for your patience!

**Closed by jchambers** 2017-05-07 18:24 UTC
Labels: bug
