### ISSUE TITLE
Handle multiple auth tokens with one connection.

### ISSUE THREAD

**Issue by bimurtobadhan** [relayrides/pushy#437] opened 2017-03-30 11:20 UTC
Hi, My company have two apps say A and B with different certificates like different teamID, keyId, topic and privateKey. I am supposed to send push to each app. So I first register with teamA, keyA, topicA and privateKeyA, then send the push. 
like apnsClient.registerSigningKey(privateKeyA,teamIdA, keyIdA, topicA);
App A receives the push. After I again register with teamB, keyB, topicB and privateKeyB like 
apnsClient.registerSigningKey(privateKeyB,teamIdB, keyIdB, topicB);
Now apple rejects the push and replies InvalidProviderToken. I am guessing that apple doesn't support multiple provider tokens for same connection. Is this really the case or I am doing something wrong here ?
Thanks in advance.

**Comment by jchambers** [comment] 2017-03-30 13:26
We're aware of this issue, and frankly aren't sure what's going on. Please see https://github.com/relayrides/pushy/issues/399#issuecomment-282306488 for discussion. In short, though, it does appear that the APNs server starts to reject notifications if presented with keys from multiple teams. It's unclear if this is the intended behavior or a bug; we're getting a slow trickle of information from Apple on the topic, but the issue is not yet resolved.

The issue here is very real, but since we're already tracking it in #399 and because there isn't something we can change on our end (that we know of, anyhow), I'm going to close this issue. Please do join the discussion in #399, though!

**Closed by jchambers** 2017-03-30 13:26 UTC
Labels: upstream issue

**Comment by jchambers** [comment] 2017-03-30 13:56
@bimurtobadhan as a point of clarification, are you seeing the same behavior as in https://forums.developer.apple.com/thread/72999? Does the connection start to reject notifications from the original team/topic, too?

Thanks!

**Comment by bimurtobadhan** [comment] 2017-03-31 04:00
Thanks for your reply. It really helps me a lot. And yes, the problem is the same as the one described in  [https://forums.developer.apple.com/thread/72999](https://forums.developer.apple.com/thread/72999) . And No the first team push messages always gets through.
