### ISSUE TITLE
Dispatch thread for PushManager died unexpectedly

### ISSUE THREAD

**Issue by stIncMale** [relayrides/pushy#182] opened 2015-06-15 12:05 UTC
Hi
We are seeing the following error each minute or two:

>level: ERROR, logger: com.relayrides.pushy.apns.PushManager$DispatchThreadExceptionHandler:

>Dispatch thread for com.relayrides.pushy.apns.PushManager(...) died unexpectedly. Please file a bug with the exception details.

>NoSuchElementException idleStateHandler

>io.netty.channel.DefaultChannelPipeline in getContextOrDie at line 967 (application)
>io.netty.channel.DefaultChannelPipeline in remove at line 305 (application)
>com.relayrides.pushy.apns.ApnsConnection in shutdownGracefully at line 638 (application)
>com.relayrides.pushy.apns.ApnsConnection in sendNotification at line 593 (application)
>com.relayrides.pushy.apns.PushManager$1 in run at line 277 (application)
>java.lang.Thread in run at line 745

Environment:
>Ubuntu 14.04.1 LTS
>netty-all-4.0.26.Final.jar
>java version "1.8.0_31"
>Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
>Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

**Comment by jchambers** [comment] 2015-06-15 14:45
I believe this is a duplicate of #144. The issue has been fixed in `master` and we're planning on putting out a new release as soon as we can resolve the [intermittent test failure](https://travis-ci.org/relayrides/pushy/builds/66438832) we've been seeing lately.

**Closed by jchambers** 2015-06-15 14:45 UTC
Labels: bug, duplicate
