### ISSUE TITLE
Unable to resolve related dependencies

### ISSUE THREAD

**Issue by amakkar** [relayrides/pushy#291] opened 2016-05-09 17:36 UTC
Hi,

Can any body list the related dependencies (in maven format) required with this project. I am getting following exception while using this library - 

```
[main] INFO com.relayrides.pushy.apns.ApnsClient - OpenSSL (via netty-tcnative) not available; will use JDK SSL provider.
[main] WARN com.relayrides.pushy.apns.ApnsClient - Asked for socket channel class to work with null event loop group, returning NioSocketChannel class.
[nioEventLoopGroup-2-1] INFO com.relayrides.pushy.apns.ApnsClient - Connected to api.development.push.apple.com/17.110.227.100:443.
Failed to send push notification.
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: io/netty/util/concurrent/PromiseCombiner
	at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:41)
	at com.naukri.ios.main.IosTestPushy.main(IosTestPushy.java:44)
Caused by: java.lang.NoClassDefFoundError: io/netty/util/concurrent/PromiseCombiner
	at com.relayrides.pushy.apns.ApnsClientHandler.write(ApnsClientHandler.java:209)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeWriteNow(ChannelHandlerInvokerUtil.java:157)
	at io.netty.channel.DefaultChannelHandlerInvoker$WriteTask.run(DefaultChannelHandlerInvoker.java:452)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: io.netty.util.concurrent.PromiseCombiner
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
[main] INFO com.relayrides.pushy.apns.ApnsClient - Disconnecting.
[nioEventLoopGroup-2-1] INFO com.relayrides.pushy.apns.ApnsClientHandler - Received GOAWAY from APNs server: {"reason":"BadCertificateEnvironment"}
[nioEventLoopGroup-2-1] INFO com.relayrides.pushy.apns.ApnsClientHandler - Received GOAWAY from APNs server: 

```

**Comment by jchambers** [comment] 2016-05-09 18:04
If you're using Maven, the dependencies should be resolved automatically if you add Pushy itself as a dependency (as [explained in the README](https://github.com/relayrides/pushy#getting-pushy)):

```
<dependency>
    <groupId>com.relayrides</groupId>
    <artifactId>pushy</artifactId>
    <version>0.7.2</version>
</dependency>
```

The other dependencies are listed right below that in the README.

If that's not working for you, could you please provide some more details as to what you've tried so far?

**Comment by amakkar** [comment] 2016-05-09 18:19
Thanks @jchambers for the response. The dependency issue is resolved but when I try to run the code (as mentioned in readme), I get the following error - 

`[main] INFO com.relayrides.pushy.apns.ApnsClient - OpenSSL (via netty-tcnative) not available; will use JDK SSL provider.
[main] WARN com.relayrides.pushy.apns.ApnsClient - Asked for socket channel class to work with null event loop group, returning NioSocketChannel class.
[nioEventLoopGroup-2-1] INFO com.relayrides.pushy.apns.ApnsClient - Connected to api.development.push.apple.com/17.172.238.203:443.
[nioEventLoopGroup-2-1] INFO com.relayrides.pushy.apns.ApnsClientHandler - Received GOAWAY from APNs server: {"reason":"BadCertificateEnvironment"}
[nioEventLoopGroup-2-1] INFO com.relayrides.pushy.apns.ApnsClientHandler - Received GOAWAY from APNs server: 
Failed to send push notification.
java.util.concurrent.ExecutionException: com.relayrides.pushy.apns.ClientNotConnectedException: Client disconnected unexpectedly.
	at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:41)
	at com.naukri.ios.main.IosTestPushy.main(IosTestPushy.java:44)
Caused by: com.relayrides.pushy.apns.ClientNotConnectedException: Client disconnected unexpectedly.
	at com.relayrides.pushy.apns.ApnsClient$2$2.run(ApnsClient.java:739)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:373)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)
Waiting for client to reconnect…
[nioEventLoopGroup-2-1] INFO com.relayrides.pushy.apns.ApnsClient - Connection to api.development.push.apple.com/17.172.238.203:443 restored.
Reconnected.
[main] INFO com.relayrides.pushy.apns.ApnsClient - Disconnecting.
`

Can you tell what might be the problem?

**Comment by jchambers** [comment] 2016-05-09 18:26
> [nioEventLoopGroup-2-1] INFO com.relayrides.pushy.apns.ApnsClientHandler - Received GOAWAY from APNs server: {"reason":"BadCertificateEnvironment"}

You're using a production certificate in the dev environment or vice versa.

This appears to be more of a general support question than a bug report or feature request, and so I'm going to close this issue. For general support questions, we recommend asking on [the mailing list](https://groups.google.com/d/forum/pushy-apns), which has a wider audience.

**Closed by jchambers** 2016-05-09 18:26 UTC
Labels: question

**Comment by marian09** [comment] 2017-01-25 16:10
Hi, I have this problem:

Exception in thread "ActiveMQ Session Task-1" java.lang.NoClassDefFoundError: com/relayrides/pushy/apns/ApnsPushNotification
Caused by: java.lang.ClassNotFoundException: com.relayrides.pushy.apns.ApnsPushNotification
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1295)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1147)
	... 10 more

I have added this one like a maven dependency on my project.
Thanks.
