### ISSUE TITLE
MockApnsServer

### ISSUE THREAD

**Issue by dant3** [relayrides/pushy#343] opened 2016-07-20 08:41 UTC
Hi,

I noticed that in test sources you have `MockApnsServer`, which is of course somewhat specific for your testing needs, but could be made a bit more generic to allow others test their implementations built on top of pushy. This would be a very good simulator to see if you really doing things right or wrong.

My proposal is to make it a bit more generic and publish it on it's own.

**Comment by jchambers** [comment] 2016-07-20 16:00
I think this is a duplicate of #313, which was closed by #315. It's scheduled for inclusion in the next release of Pushy.

**Closed by jchambers** 2016-07-20 16:00 UTC
Labels: duplicate

**Comment by dant3** [comment] 2016-07-25 09:16
It really is. Looking forward for a next release.
