### ISSUE TITLE
Connection pooling

### ISSUE THREAD

**Issue by janzar** [relayrides/pushy#477] opened 2017-06-07 12:21 UTC
Have seen commits in branch on the topic, but not sure about final outcome. It would be nice to have it in library itself, because it seems that Apple is able to handle about 500 notifications per second, and if we send more, we need to introduce pool of connections outside of library.

Thanks,
Z.

**Comment by jchambers** [comment] 2017-06-07 13:34
This is a duplicate of #399; please see that issue for discussion. We do still hope to revisit the issue eventually, but certain upstream design choices have made that effort difficult so far. Let's keep conversation about the feature focused in #399 for now.

In the meantime, it sounds like you're trying to open a *lot* of connections in rapid succession. Please let me take this opportunity to point out that, once you've opened a connection with an `ApnsClient`, you can use that client to send lots of notifications. You don't need to—and shouldn't—open a new connection for each push notification.

Hope that helps!

**Closed by jchambers** 2017-06-07 13:34 UTC
Labels: duplicate

**Comment by janzar** [comment] 2017-06-07 14:37
ok
