### ISSUE TITLE
failed to find rejected notification with sequence number 0

### ISSUE THREAD

**Issue by U-238** [relayrides/pushy#150] opened 2015-02-18 07:17 UTC
I get this error when calling shutdown(). Calling shutdown() also resends all the push notifications that I had sent during that session!

```
PushManager-connection-0 failed to find rejected notification with sequence number 0 (buffer has range 1 to 11); this may mean the sent notification buffer is too small. Please report this as a bug.
```

**Comment by U-238** [comment] 2015-02-18 07:32
Here is the bug again with trace logging enabled. In the below case, after I called shutdown(), it sent me the same message over and over again (I received it on my phone constantly) until I killed the process with "kill -9"

```
INFO  2015-02-18 18:26:33,254 [main] - OurcastPushManager starting.
DEBUG 2015-02-18 18:26:33,342 [main] - OurcastPushManager-connection-0 beginning connection process.
DEBUG 2015-02-18 18:26:34,092 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-0 connected; waiting for TLS handshake.
DEBUG 2015-02-18 18:26:34,815 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-0 successfully completed TLS handshake.
TRACE 2015-02-18 18:26:34,815 [nioEventLoopGroup-2-1] - Connection succeeded: ApnsConnection [name=OurcastPushManager-connection-0]
INFO  2015-02-18 18:27:00,848 [pool-1-thread-4] - Sent push #20 to 39490a6c7717092c6b667c969f207f8dce43bd8de030bc316db80472125c71a2 with message Hello test
TRACE 2015-02-18 18:27:00,857 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-0 sending SendableApnsPushNotification [sequenceNumber=1, token=39490a6c7717092c6b667c969f207f8dce43bd8de030bc316db80472125c71a2, payload={"aps":{"alert":"Hello test","sound":"default"}}, deliveryInvalidation=Wed Feb 18 18:29:00 EST 2015]
TRACE 2015-02-18 18:27:00,860 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-0 successfully wrote notification 1
INFO  2015-02-18 18:27:26,075 [ShutdownHook] - APNS daemon got shutdown signal
INFO  2015-02-18 18:27:28,866 [main] - OurcastPushManager shutting down.
DEBUG 2015-02-18 18:27:28,867 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-0 sending known-bad notification to shut down.
TRACE 2015-02-18 18:27:28,869 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-0 successfully wrote known-bad notification 2
DEBUG 2015-02-18 18:27:29,113 [nioEventLoopGroup-2-1] - APNs gateway rejected notification with sequence number 0 from OurcastPushManager-connection-0 (MISSING_TOKEN).
ERROR 2015-02-18 18:27:29,113 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-0 failed to find rejected notification with sequence number 0 (buffer has range 1 to 1); this may mean the sent notification buffer is too small. Please report this as a bug.
TRACE 2015-02-18 18:27:29,113 [nioEventLoopGroup-2-1] - ApnsConnection [name=OurcastPushManager-connection-0] returned 1 unprocessed notifications
TRACE 2015-02-18 18:27:29,116 [nioEventLoopGroup-2-1] - Connection closed: ApnsConnection [name=OurcastPushManager-connection-0]
DEBUG 2015-02-18 18:27:29,117 [pool-3-thread-1] - OurcastPushManager-connection-1 beginning connection process.
DEBUG 2015-02-18 18:27:29,372 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-1 connected; waiting for TLS handshake.
DEBUG 2015-02-18 18:27:29,930 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-1 successfully completed TLS handshake.
TRACE 2015-02-18 18:27:29,930 [nioEventLoopGroup-2-1] - Connection succeeded: ApnsConnection [name=OurcastPushManager-connection-1]
TRACE 2015-02-18 18:27:29,930 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-1 sending SendableApnsPushNotification [sequenceNumber=1, token=39490a6c7717092c6b667c969f207f8dce43bd8de030bc316db80472125c71a2, payload={"aps":{"alert":"Hello test","sound":"default"}}, deliveryInvalidation=Wed Feb 18 18:29:00 EST 2015]
TRACE 2015-02-18 18:27:29,931 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-1 successfully wrote notification 1
DEBUG 2015-02-18 18:27:29,931 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-1 sending known-bad notification to shut down.
TRACE 2015-02-18 18:27:29,931 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-1 successfully wrote known-bad notification 2
DEBUG 2015-02-18 18:27:30,186 [nioEventLoopGroup-2-1] - APNs gateway rejected notification with sequence number 0 from OurcastPushManager-connection-1 (MISSING_TOKEN).
ERROR 2015-02-18 18:27:30,186 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-1 failed to find rejected notification with sequence number 0 (buffer has range 1 to 1); this may mean the sent notification buffer is too small. Please report this as a bug.
TRACE 2015-02-18 18:27:30,186 [nioEventLoopGroup-2-1] - ApnsConnection [name=OurcastPushManager-connection-1] returned 1 unprocessed notifications
TRACE 2015-02-18 18:27:30,187 [nioEventLoopGroup-2-1] - Connection closed: ApnsConnection [name=OurcastPushManager-connection-1]
DEBUG 2015-02-18 18:27:30,188 [pool-3-thread-1] - OurcastPushManager-connection-2 beginning connection process.
DEBUG 2015-02-18 18:27:30,469 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-2 connected; waiting for TLS handshake.
DEBUG 2015-02-18 18:27:31,074 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-2 successfully completed TLS handshake.
TRACE 2015-02-18 18:27:31,074 [nioEventLoopGroup-2-1] - Connection succeeded: ApnsConnection [name=OurcastPushManager-connection-2]
TRACE 2015-02-18 18:27:31,075 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-2 sending SendableApnsPushNotification [sequenceNumber=1, token=39490a6c7717092c6b667c969f207f8dce43bd8de030bc316db80472125c71a2, payload={"aps":{"alert":"Hello test","sound":"default"}}, deliveryInvalidation=Wed Feb 18 18:29:00 EST 2015]
TRACE 2015-02-18 18:27:31,075 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-2 successfully wrote notification 1
DEBUG 2015-02-18 18:27:31,075 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-2 sending known-bad notification to shut down.
TRACE 2015-02-18 18:27:31,076 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-2 successfully wrote known-bad notification 2
DEBUG 2015-02-18 18:27:31,357 [nioEventLoopGroup-2-1] - APNs gateway rejected notification with sequence number 0 from OurcastPushManager-connection-2 (MISSING_TOKEN).
ERROR 2015-02-18 18:27:31,358 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-2 failed to find rejected notification with sequence number 0 (buffer has range 1 to 1); this may mean the sent notification buffer is too small. Please report this as a bug.
TRACE 2015-02-18 18:27:31,358 [nioEventLoopGroup-2-1] - ApnsConnection [name=OurcastPushManager-connection-2] returned 1 unprocessed notifications
TRACE 2015-02-18 18:27:31,358 [nioEventLoopGroup-2-1] - Connection closed: ApnsConnection [name=OurcastPushManager-connection-2]
DEBUG 2015-02-18 18:27:31,359 [pool-3-thread-1] - OurcastPushManager-connection-3 beginning connection process.
DEBUG 2015-02-18 18:27:31,607 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-3 connected; waiting for TLS handshake.
DEBUG 2015-02-18 18:27:32,149 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-3 successfully completed TLS handshake.
TRACE 2015-02-18 18:27:32,149 [nioEventLoopGroup-2-1] - Connection succeeded: ApnsConnection [name=OurcastPushManager-connection-3]
TRACE 2015-02-18 18:27:32,150 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-3 sending SendableApnsPushNotification [sequenceNumber=1, token=39490a6c7717092c6b667c969f207f8dce43bd8de030bc316db80472125c71a2, payload={"aps":{"alert":"Hello test","sound":"default"}}, deliveryInvalidation=Wed Feb 18 18:29:00 EST 2015]
TRACE 2015-02-18 18:27:32,150 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-3 successfully wrote notification 1
DEBUG 2015-02-18 18:27:32,150 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-3 sending known-bad notification to shut down.
TRACE 2015-02-18 18:27:32,151 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-3 successfully wrote known-bad notification 2
DEBUG 2015-02-18 18:27:32,400 [nioEventLoopGroup-2-1] - APNs gateway rejected notification with sequence number 0 from OurcastPushManager-connection-3 (MISSING_TOKEN).
ERROR 2015-02-18 18:27:32,401 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-3 failed to find rejected notification with sequence number 0 (buffer has range 1 to 1); this may mean the sent notification buffer is too small. Please report this as a bug.
TRACE 2015-02-18 18:27:32,401 [nioEventLoopGroup-2-1] - ApnsConnection [name=OurcastPushManager-connection-3] returned 1 unprocessed notifications
TRACE 2015-02-18 18:27:32,401 [nioEventLoopGroup-2-1] - Connection closed: ApnsConnection [name=OurcastPushManager-connection-3]
DEBUG 2015-02-18 18:27:32,402 [pool-3-thread-1] - OurcastPushManager-connection-4 beginning connection process.
DEBUG 2015-02-18 18:27:32,652 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-4 connected; waiting for TLS handshake.
DEBUG 2015-02-18 18:27:33,192 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-4 successfully completed TLS handshake.
TRACE 2015-02-18 18:27:33,192 [nioEventLoopGroup-2-1] - Connection succeeded: ApnsConnection [name=OurcastPushManager-connection-4]
TRACE 2015-02-18 18:27:33,193 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-4 sending SendableApnsPushNotification [sequenceNumber=1, token=39490a6c7717092c6b667c969f207f8dce43bd8de030bc316db80472125c71a2, payload={"aps":{"alert":"Hello test","sound":"default"}}, deliveryInvalidation=Wed Feb 18 18:29:00 EST 2015]
TRACE 2015-02-18 18:27:33,193 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-4 successfully wrote notification 1
DEBUG 2015-02-18 18:27:33,193 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-4 sending known-bad notification to shut down.
TRACE 2015-02-18 18:27:33,193 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-4 successfully wrote known-bad notification 2
DEBUG 2015-02-18 18:27:33,445 [nioEventLoopGroup-2-1] - APNs gateway rejected notification with sequence number 0 from OurcastPushManager-connection-4 (MISSING_TOKEN).
ERROR 2015-02-18 18:27:33,445 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-4 failed to find rejected notification with sequence number 0 (buffer has range 1 to 1); this may mean the sent notification buffer is too small. Please report this as a bug.
TRACE 2015-02-18 18:27:33,445 [nioEventLoopGroup-2-1] - ApnsConnection [name=OurcastPushManager-connection-4] returned 1 unprocessed notifications
TRACE 2015-02-18 18:27:33,446 [nioEventLoopGroup-2-1] - Connection closed: ApnsConnection [name=OurcastPushManager-connection-4]
DEBUG 2015-02-18 18:27:33,446 [pool-3-thread-1] - OurcastPushManager-connection-5 beginning connection process.
DEBUG 2015-02-18 18:27:33,713 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-5 connected; waiting for TLS handshake.
DEBUG 2015-02-18 18:27:34,252 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-5 successfully completed TLS handshake.
TRACE 2015-02-18 18:27:34,253 [nioEventLoopGroup-2-1] - Connection succeeded: ApnsConnection [name=OurcastPushManager-connection-5]
TRACE 2015-02-18 18:27:34,253 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-5 sending SendableApnsPushNotification [sequenceNumber=1, token=39490a6c7717092c6b667c969f207f8dce43bd8de030bc316db80472125c71a2, payload={"aps":{"alert":"Hello test","sound":"default"}}, deliveryInvalidation=Wed Feb 18 18:29:00 EST 2015]
TRACE 2015-02-18 18:27:34,254 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-5 successfully wrote notification 1
DEBUG 2015-02-18 18:27:34,254 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-5 sending known-bad notification to shut down.
TRACE 2015-02-18 18:27:34,255 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-5 successfully wrote known-bad notification 2
DEBUG 2015-02-18 18:27:34,506 [nioEventLoopGroup-2-1] - APNs gateway rejected notification with sequence number 0 from OurcastPushManager-connection-5 (MISSING_TOKEN).
ERROR 2015-02-18 18:27:34,506 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-5 failed to find rejected notification with sequence number 0 (buffer has range 1 to 1); this may mean the sent notification buffer is too small. Please report this as a bug.
TRACE 2015-02-18 18:27:34,506 [nioEventLoopGroup-2-1] - ApnsConnection [name=OurcastPushManager-connection-5] returned 1 unprocessed notifications
TRACE 2015-02-18 18:27:34,507 [nioEventLoopGroup-2-1] - Connection closed: ApnsConnection [name=OurcastPushManager-connection-5]
DEBUG 2015-02-18 18:27:34,507 [pool-3-thread-1] - OurcastPushManager-connection-6 beginning connection process.
DEBUG 2015-02-18 18:27:34,751 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-6 connected; waiting for TLS handshake.
DEBUG 2015-02-18 18:27:35,283 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-6 successfully completed TLS handshake.
TRACE 2015-02-18 18:27:35,283 [nioEventLoopGroup-2-1] - Connection succeeded: ApnsConnection [name=OurcastPushManager-connection-6]
TRACE 2015-02-18 18:27:35,284 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-6 sending SendableApnsPushNotification [sequenceNumber=1, token=39490a6c7717092c6b667c969f207f8dce43bd8de030bc316db80472125c71a2, payload={"aps":{"alert":"Hello test","sound":"default"}}, deliveryInvalidation=Wed Feb 18 18:29:00 EST 2015]
TRACE 2015-02-18 18:27:35,285 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-6 successfully wrote notification 1
DEBUG 2015-02-18 18:27:35,285 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-6 sending known-bad notification to shut down.
TRACE 2015-02-18 18:27:35,285 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-6 successfully wrote known-bad notification 2
DEBUG 2015-02-18 18:27:35,530 [nioEventLoopGroup-2-1] - APNs gateway rejected notification with sequence number 0 from OurcastPushManager-connection-6 (MISSING_TOKEN).
ERROR 2015-02-18 18:27:35,531 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-6 failed to find rejected notification with sequence number 0 (buffer has range 1 to 1); this may mean the sent notification buffer is too small. Please report this as a bug.
TRACE 2015-02-18 18:27:35,531 [nioEventLoopGroup-2-1] - ApnsConnection [name=OurcastPushManager-connection-6] returned 1 unprocessed notifications
TRACE 2015-02-18 18:27:35,531 [nioEventLoopGroup-2-1] - Connection closed: ApnsConnection [name=OurcastPushManager-connection-6]
DEBUG 2015-02-18 18:27:35,531 [pool-3-thread-1] - OurcastPushManager-connection-7 beginning connection process.
DEBUG 2015-02-18 18:27:35,788 [nioEventLoopGroup-2-1] - OurcastPushManager-connection-7 connected; waiting for TLS handshake.
```

**Comment by dwxw** [comment] 2015-02-18 16:11
Having never seen this before today, I'm now getting what looks like the same problem.  Seems to happen intermittently.  When it does occur, I get the notification sent multiple times, even though the PushManager reports it failed to connect to the service.

**Comment by jchambers** [comment] 2015-02-18 16:39
Bizarre. This sounds like a serious problem, and possibly something originating upstream. Thank you, everybody, for the detailed information. We'll do our best to get to the bottom of this as quickly as possible.

**Comment by jchambers** [comment] 2015-02-18 16:40
…although this does appear to be a duplicate of #149. Closing as such.

**Closed by jchambers** 2015-02-18 16:40 UTC
