### ISSUE TITLE
Duplicate notifications delivered under v0.13.5

### ISSUE THREAD

**Issue by browanchenjing** [relayrides/pushy#652] opened 2018-12-04 07:03 UTC
this version  each message will be pushed twice

**Comment by jchambers** [comment] 2018-12-04 15:12
@browanchenjing Can you please provide some more detail?

1. Does this happen with every notification?
2. Are you sure the problem started with v0.13.5? Does it go away if you use v0.13.4, for example?
3. If this _does_ happen with every notification, could you please [add a frame logger](http://relayrides.github.io/pushy/apidocs/0.13/com/turo/pushy/apns/ApnsClientBuilder.html#setFrameLogger-io.netty.handler.codec.http2.Http2FrameLogger-), send a notification, and share the logs here?

Thank you!

**Comment by jchambers** [comment] 2018-12-05 16:55
To be clear: I am _not_ able to reproduce this issue locally, so I don't think we can make any progress on this issue without more information.

**Comment by jchambers** [comment] 2018-12-08 15:41
I'm going to close this for now because I can't reproduce the issue and because it does not appear to be widespread. @browanchenjing if you have the opportunity to provide more information, please do and we'll happily re-open this issue!

**Closed by jchambers** 2018-12-08 15:41 UTC

**Comment by browanchenjing** [comment] 2018-12-10 05:44
This problem happen when App cut to the background from v0.11.0,when kill the App process,push message normal.

**Comment by jchambers** [comment] 2018-12-12 18:07
Thank you for the additional detail, but I still have some questions:

1. Again, can you reproduce this every time? Does it happen with every notification, or does it just happen sometimes?
2. Can you please use a frame logger to verify that Pushy is actually sending the notification more than once?
