### ISSUE TITLE
proxy TLS handshake timed out

### ISSUE THREAD

**Issue by ioilala** [relayrides/pushy#385] opened 2016-11-18 11:29 UTC
when I use a proxy as the README shows:

```
 .setProxyHandlerFactory(new Socks5ProxyHandlerFactory(
				            new InetSocketAddress("172.17.0.254", 7080)))
```

I get the follow exception
```
2016-11-18 19:16:14,021 13471 [main] (ApnsMessageHttp2Consumer.java:160) INFO  com.xxx.xxx.apns.ApnsMessageHttp2Consumer - iosconnect to api.development.push.apple.com fail!javax.net.ssl.SSLException: handshake timed out
2016-11-18 19:16:14,021 13471 [nioEventLoopGroup-2-1] (ApnsClient.java:470) INFO  com.relayrides.pushy.apns.ApnsClient - Failed to connect.
javax.net.ssl.SSLException: handshake timed out
	at io.netty.handler.ssl.SslHandler.handshake(...)(Unknown Source)
```

I can successfully send push in the case without proxy.The proxy has been proved to be feasible in the brower. 
**My Jdk version:1.8.0.0_66
ALPN version:alpn-boot 8.1.6.v20151105**
So I wonder if anyone encounter the same problem and what could be the possible reason?Thank you~

**Comment by jchambers** [comment] 2016-11-18 18:44
Respectfully, this sounds more like a proxy configuration issue than a bug within Pushy. I'm unable to reproduce the issue locally, and without much more specific information, there really isn't anything we can do to move this forward from our end. With that in mind, I don't think we have any choice but to close this issue.

That said, if you can give us more specific information about what's going wrong, we'll happily revisit the issue!

**Closed by jchambers** 2016-11-18 18:44 UTC
