### ISSUE TITLE
UDP Ports leak on calling close on ApnsClient - 0.13.5

### ISSUE THREAD

**Issue by abahuguna** [relayrides/pushy#675] opened 2019-01-21 09:34 UTC
I have a code where I keep fixed size cache of APNS clients. On eviction from the cache, apns clients are closed.
```
final Future<Void> closeFuture = entry.getKey().getApnsClient().close().addListener(new GenericFutureListener<Future<Void>>() {
	@Override
	public void operationComplete(Future<Void> future) throws Exception {
		if (future.isSuccess()) {
		    logger.info("Pushy APNS closed call success");
                } else {
		   logger.info("Pushy APNS closed call failed");
                }
        } 
});
```

I have confirmed the number of clients evicted from cache are equal to number of clients on which close got called successfully. But noticed the number of udp ports opened by the java process keeps increasing very highly. On enabling pushy and netty logging it seems these ports are opened due to 
RoundRobinDnsAddressResolverGroup and on close these ports are not closing. This open port count only keeps increasing due to large volume of evictions and close and over a period of some days app becomes unresponsive and needs a restart.

`lsof -n  -p <pid> | sed -n '1p;/UDP/p' | wc -l`

I made local changes to Pushy in `ApnsChannelFactory:: this.bootstrapTemplate.resolver` to use DefaultAddressResolverGroup.INSTANCE and number of open udp ports became stable.

So [https://github.com/relayrides/pushy/issues/632](url) doesn't seem to be fixed

**Comment by rohitsahay2000** [comment] 2019-01-21 12:37
+1 Facing the same issue with latest pushy. The end result seems to be High CPU Usage over a long run. Have opened a bug with netty as well: https://github.com/netty/netty/issues/8553

**Comment by jchambers** [comment] 2019-01-21 16:56
I've written a simple application to replicate what I understand to be the core of your problem:

```java
final ApnsSigningKey signingKey = ApnsSigningKey.loadFromPkcs8File(SIGNING_KEY_FILE, TEAM_ID, KEY_UD);
final SimpleApnsPushNotification pushNotification = new SimpleApnsPushNotification(TOKEN, TOPIC, "{}");

while (true) {
    final ApnsClient client = new ApnsClientBuilder()
            .setApnsServer(ApnsClientBuilder.DEVELOPMENT_APNS_HOST)
            .setSigningKey(signingKey)
            .build();

    client.sendNotification(pushNotification).await();
    client.close().await();

    Thread.sleep(1000);
}
```

Obviously, the constants are defined elsewhere.

Running the application for several minutes shows no increase in the number of open UDP ports. I am unable to reproduce this problem, and will close this issue for now. We'll happily reopen the ticket if you can provide a minimal, but complete test case that demonstrates this problem.

As I have explained to @rohitsahay2000 before (and I presume you two work together), I strongly suspect you are—somewhere—failing to close `ApnsClient` instances. I am open to being convinced otherwise, but you'll need to provide a test case for that to happen.

**Comment by abahuguna** [comment] 2019-01-22 15:42
@jchambers Thanks for reply, I will re-verify the part of not closing apns clients and get back with a reproducer. 

Had couple of questions -
1. From snippet you provided, what is preferred way of closing multiple apns clients on cases where apns clients are cached and will be evicted on TTL expiry or cache gets filled while java app is continuously running. Should I call `client.close()` and not check on Future on each evicted apns client or use `client.close().await();`

2. Regarding my comment regarding UDP ports
Till 0.12.1 of pushy, you had something like following in constructor [https://github.com/relayrides/pushy/blob/pushy-0.12.1/pushy/src/main/java/com/turo/pushy/apns/ApnsChannelFactory.java](url)
```this.bootstrapTemplate.resolver(proxyHandlerFactory == null ?
DefaultAddressResolverGroup.INSTANCE : NoopAddressResolverGroup.INSTANCE);```

When I reverted to the DefaultAddressResolverGroup instead of RoundRobinDnsAddressResolverGroup used in latter iteration of Pushy, the same code with modified pushy jar ran better. Since DefaultAddressResolverGroup was used previously in pushy, do you see issue with APNS clients still using old way of Address Resolver like 0.12.1 and older pushy clients with respect to sending notification to APN service.
(I will investigate more on Round Robin DNS causing issue in those server and share my finding )

**Comment by eugeneseppel** [comment] 2019-04-15 14:58
Please reopen this issue.
I've experienced this bug in prod after updating to new Pushy and could easily reproduce situation:
In example provided by @jchambers  add the following line
.setEventLoopGroup(new NioEventLoopGroup(1))
to the ApnsClient builder.
After that this small test will leak and open one more udp port after each iteration.
This caused by "this.shouldShutDownEventLoopGroup = false;" in ApnsClient ctor.

**Comment by jchambers** [comment] 2019-04-16 17:26
@eugeneseppel I still don't think this is an issue.

I can, indeed, reproduce the problem by creating a `new NioEventLoopGroup(1)` on every iteration of the loop in the [example above](https://github.com/relayrides/pushy/issues/675#issuecomment-456139694), but _only if I don't close the event loop group_. Closing the event loop group after shutting down the client _or_ reusing the same caller-provided event loop group resolves the issue.

Failing to close the event loop group is a bigger problem. As the `ApnsClient` docs explain:

> Callers may optionally specify an `EventLoopGroup` when constructing a new client. If no event loop group is specified, clients will create and manage their own single-thread event loop group…
>
> If an event loop group was specified at construction time, callers should shut down that event loop group when all clients using that group have been disconnected.

If you're not cleaning up your event loop groups, you're _also_ leaking threads, memory, and possibly open network connections. There may be room to improve the documentation in this case, but I still don't think there's an actual technical problem with releasing UDP ports when a client shuts down.

**Comment by eugeneseppel** [comment] 2019-04-29 13:29
@jchambers I'm sorry for late answer -- please reopen this ticket, because reusing the same caller-provided event loop doesn't solve the issue with port leaking.
This code reproduces the problem:
```
    @Test
    public void test1() throws Exception {
        final SimpleApnsPushNotification pushNotification
                = new SimpleApnsPushNotification("apns:xxxxxxxxxxxxxxxxxxxxxxxx",
                DEFAULT_TOPIC, "{}");

        NioEventLoopGroup group = new NioEventLoopGroup(1);
        while (true) {
            final ApnsClient client = new ApnsClientBuilder()
                    .setApnsServer(ApnsClientBuilder.DEVELOPMENT_APNS_HOST)
                    .setSigningKey(signingKey)
                    .setEventLoopGroup(group)
                    .build();

            client.sendNotification(pushNotification).await();
            client.close().await();

            Thread.sleep(1000);
        }
    }
```
this 
$ while true; do netstat -lpn --udp|grep java; sleep 1; done
shows port leak on every iteration.

**Comment by jchambers** [comment] 2019-06-01 15:24
Okay; I _can_ reproduce the problem with the latest example. Will investigate.

**Comment by jchambers** [comment] 2019-06-01 20:10
I've produced a minimal (i.e. non-Pushy) reproduction case and opened https://github.com/netty/netty/issues/9212 as an upstream issue.

**Comment by jchambers** [comment] 2019-06-02 18:24
Going one further, I've also opened netty/netty#9214 as a potential upstream fix for this issue.

**Comment by eugeneseppel** [comment] 2019-06-03 08:18
Thank you for the investigation!

**Comment by jchambers** [comment] 2019-06-04 12:17
netty/netty#9214 has been merged and should go out as part of [Netty 4.1.37](https://github.com/netty/netty/milestone/210).

**Comment by eugeneseppel** [comment] 2019-06-04 14:47
Thank you, @jchambers ! I'm looking forward for that version of Netty.

**Comment by abahuguna** [comment] 2019-06-04 17:44
Thank you @eugeneseppel and @jchambers for the fix.

**Comment by jchambers** [comment] 2019-06-04 19:06
Also, please accept my apologies for the incorrect diagnosis earlier. That certainly delayed getting this issue fixed.

**Closed** 2019-06-28 19:23 UTC
Labels: bug, upstream issue

**Comment by eugeneseppel** [comment] 2019-07-03 13:40
Thank you so much, @jchambers!

**Comment by eugeneseppel** [comment] 2019-08-05 08:26
@jchambers I solicit for reopening this ticket again. After several weeks running in production I've figured out that experience a memory leak. 
There is a unit tests that shows this leak:
ApnsClientTest.java, add this one:
```
    @Test
    public void test1() throws Exception {
        final SimpleApnsPushNotification pushNotification
                = new SimpleApnsPushNotification("apns:1111111111111111111111111111111111111111111111111111111111111111",
                "com.twilio.www", "{}");

        NioEventLoopGroup group = new NioEventLoopGroup(2);
        for(int i = 0; ; i++) {
            final ApnsClient client = new ApnsClientBuilder()
                    .setApnsServer("www.something.com") // to not flood apns
                    .setSigningKey(signingKey)
                    .setEventLoopGroup(group)
                    .build();
            Thread.sleep(10);
            client.sendNotification(pushNotification).await();
            client.close().await();

            if (i % 50 == 0) {
                Runtime.getRuntime().gc();
            }

            System.out.printf("y=%d\n", i);
        }
    }
```
Please run this test until 16000 iterations with current version of pushy and run 
$ while true; do ps axu|grep test1|grep -v grep|awk '{print $5,$6}'; sleep 2; done
in terminal to check RSS is increasing
After that you can eliminate usage/creation of RoundRobinAddressResolver in ApnsChannelFactory:

>  remove private final AddressResolverGroup addressResolverGroup;
>          this.bootstrapTemplate.resolver(proxyHandlerFactory == null ?
>                  DefaultAddressResolverGroup.INSTANCE : NoopAddressResolverGroup.INSTANCE);

rerun this test and see that RSS is quite stable.

Moreover I have to add that currently in production our project consumes ~100 open UDP ports for resolver. (previously was ~1). It is not a serious issue for our usage pattern but quite strange why one need 100 ports to resolve just 2 APNS domain names
