### ISSUE TITLE
java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed

### ISSUE THREAD

**Issue by ivanursul** [relayrides/pushy#411] opened 2017-01-13 06:28 UTC
```
java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed.
	at com.relayrides.pushy.apns.ApnsClient$2.operationComplete(ApnsClient.java:464)
	at com.relayrides.pushy.apns.ApnsClient$2.operationComplete(ApnsClient.java:456)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:488)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:111)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1058)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:686)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:664)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:607)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:635)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:619)
	at io.netty.channel.ChannelOutboundHandlerAdapter.close(ChannelOutboundHandlerAdapter.java:71)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:635)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:619)
	at io.netty.handler.ssl.SslHandler$8.operationComplete(SslHandler.java:1448)
	at io.netty.handler.ssl.SslHandler$8.operationComplete(SslHandler.java:1439)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:488)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:170)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
	at io.netty.handler.ssl.SslHandler.safeClose(SslHandler.java:1439)
	at io.netty.handler.ssl.SslHandler.closeOutboundAndChannel(SslHandler.java:1261)
	at io.netty.handler.ssl.SslHandler.close(SslHandler.java:448)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:635)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:619)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:476)
	at io.netty.handler.ssl.ApplicationProtocolNegotiationHandler.exceptionCaught(ApplicationProtocolNegotiationHandler.java:122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:275)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:267)
	at io.netty.handler.ssl.SslHandler.exceptionCaught(SslHandler.java:746)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:861)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:226)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:210)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:203)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1322)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:210)
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:902)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:311)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:639)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

So, it looks like it's failing on this line:

```
                                    ApnsClient.this.connectionReadyPromise.tryFailure(
                                            new IllegalStateException("Channel closed before HTTP/2 preface completed."));
```

What are the possible options to fix this error?

**Comment by jchambers** [comment] 2017-01-13 16:52
…though to be clear, this is absolutely expected behavior. All this means is that *something* went wrong when connecting (bad certificate? transient network shenanigans?), and the connection closed—probably because the server closed it—before we completed the handshake. This is very unlikely to be a bug in Pushy itself.

I've opened #412 to track progress on more accurately reporting root causes, but I don't think there's any engineering change we'll be able to make on our end that resolves your specific problem. With that in mind, I'm going to close this issue.

I emphasize, though, that we'd be happy to help you figure out what's going on here. I think that's more of a general support question, though, and encourage you to raise the issue on [the mailing list](https://groups.google.com/d/forum/pushy-apns).

Cheers!

**Closed by jchambers** 2017-01-13 16:52 UTC

**Comment by filiphr** [comment] 2017-11-23 07:30
I know that this is on old issue, but just to give my info over a possible solution to the error that occurs. In my case I was getting that error as I was using a different version of netty than the one used by pushy. Once I changed my version to match the one from pushy the problem went away.
