### ISSUE TITLE
ApnsClientHandler.close bug

### ISSUE THREAD

**Issue by Tielancy** [relayrides/pushy#495] opened 2017-07-17 06:44 UTC
close:
```
@Override
 public void close(final ChannelHandlerContext context, final ChannelPromise promise) throws Exception {
        super.close(context, promise);
        final ClientNotConnectedException clientNotConnectedException =
                new ClientNotConnectedException("Client disconnected unexpectedly.");
        for (final Promise<PushNotificationResponse<ApnsPushNotification>> responsePromise : this.responsePromises.values()) {
            responsePromise.tryFailure(clientNotConnectedException);
        }
        this.responsePromises.clear();
    }
```

write:
```
@Override
    public void write(final ChannelHandlerContext context, final Object message, final ChannelPromise writePromise) throws Http2Exception, InvalidKeyException, NoSuchAlgorithmException {
        if (message instanceof PushNotificationAndResponsePromise) {
            final PushNotificationAndResponsePromise pushNotificationAndResponsePromise =
                    (PushNotificationAndResponsePromise) message;

            final ApnsPushNotification pushNotification = pushNotificationAndResponsePromise.getPushNotification();

            if (this.responsePromises.containsKey(pushNotification)) {
                writePromise.tryFailure(new PushNotificationStillPendingException());
            } else {
                this.responsePromises.put(pushNotification, pushNotificationAndResponsePromise.getResponsePromise());

                pushNotificationAndResponsePromise.getResponsePromise().addListener(new GenericFutureListener<Future<PushNotificationResponse<ApnsPushNotification>>> () {

                    @Override
                    public void operationComplete(final Future<PushNotificationResponse<ApnsPushNotification>> future) {
                        // Regardless of the outcome, when the response promise is finished, we want to remove it from
                        // the map of pending promises.
                        ApnsClientHandler.this.responsePromises.remove(pushNotification);
                    }
                });
                this.write(context, pushNotification, writePromise);
            }
           ...

```
throw ConcurrentModificationException caused by codes:
 `for (final Promise<PushNotificationResponse<ApnsPushNotification>> responsePromise : this.responsePromises.values())`
and 
 `ApnsClientHandler.this.responsePromises.remove(pushNotification)`

**Comment by panchenko** [comment] 2017-07-17 07:17
Looks like a duplicate of #479

**Comment by jchambers** [comment] 2017-07-17 15:20
> Looks like a duplicate of #479

Agreed. I'm pretty sure this is fixed.

**Closed by jchambers** 2017-07-17 15:20 UTC
Labels: bug, duplicate
