### ISSUE TITLE
Responses in operationComplete missed

### ISSUE THREAD

**Issue by manusdiaz** [relayrides/pushy#256] opened 2016-03-24 20:27 UTC
First of all, thank you very much for this library. I think it’s very promising and the only one I’ve seen that uses http2 for apns connection. 

I need to change my old connector, implemented with javapns and I’m testing pushy with two different behaviours: synchronous and asynchronous.

- Test 1. Sending 10 notifications (for loop):
    +No problem detected with synchronous version, resolving future with .get(). 
    +With asynchronous version, i.e, resolving future with a listener, multiple responses are not fired in operationComplete or exceptions, but all notifications are delivered to the device.

- Test 2. Sending 1000 notifications (for loop):
    +No problem detected with synchronous version.
    +With asynchronous version (listener) multiple notifications are delivered to device, but  multiple responses are not fired in operationComplete and during execution, in log appears this error (several times):

```
mar 24, 2016 3:46:30 PM io.netty.util.concurrent.PromiseNotifier operationComplete
WARNING: Failed to mark a promise as failure because it's done already: DefaultChannelPromise@7cbb6f2(failure: javax.net.ssl.SSLException: SSLEngine closed already)
io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:144)…
```

In addition, there are multiple connection problems.

It’s mandatory to detect if notifications have been rejected, accepted or any connection problem with apns for each notification. With synchronous behaviour I have all this information, but the performance is much less.
 
Using liteners, I’m not sure if I have detected a bug or I’m coding something wrong, but the testing code it’s very simple. Let me now if the information enclosed it’s enough to understand the problem and thank you very much in advance.

Platform and dependences:
- Jdk 1.8.0_74
- Pushy-0.5.2
- Netty -*-4.1.0CR2
- Slf4j-api-1.7.6
- alpn-boot-8.1.7.v20160121
- alpn-api-1.1.2.v20150522
- gson-2.5

Code:

```java
public static void main(String[] args) {
...
apnsClient = new ApnsClient<>(new File(appleKeystore),
					passAppleKeystore, new NioEventLoopGroup(10));
Future<Void> connectFuture = apnsClient
					.connect(ApnsClient.DEVELOPMENT_APNS_HOST);

for (int i = 0; i < 1000; i++) {
		sendNotificationAsync(apnsClient, pushNotification, counter, i);
		// sendNotificationSync(apnsClient, pushNotification, counter, i);
}
}

private static void sendNotificationAsync(
			ApnsClient<SimpleApnsPushNotification> apnsClient,
			SimpleApnsPushNotification pushNotification, final Counter counter,
			int i) {
		
	try{		
	final Future<PushNotificationResponse<SimpleApnsPushNotification>> sendNotificationFuture = apnsClient					.sendNotification(pushNotification);
sendNotificationFuture	.addListener(new ListenerWrapper<Future>(i) {
		@Override
public void onOperationComplete(final Future future, Object params) throws Exception {
			if (future.isSuccess()) {
PushNotificationResponse< > pushNotificationReponse = future.get();
				if (pushNotificationReponse.isAccepted()) {
					System.out.println(params + " Success");
				} 
}else {
System.out.println("Notification rejected: "+ pushNotificationReponse.getRejectionReason());
				}
			}
			 else {
				System.out.println(params + " Failed!!!");
			}});

		} catch (final Throwable t) {
			counter.addFailure();
			System.err.println("Failed to send push notification.");
			// e.printStackTrace();
		}
		}
	}

public abstract class ListenerWrapper<F extends Future<?>> implements GenericFutureListener<F>{
	Object params;
	
	public ListenerWrapper(Object params){
		this.params=params;
	}
	
	@Override
	public void operationComplete(F arg0) throws Exception {
		this.onOperationComplete(arg0, params);
		
	}
	
	public abstract void onOperationComplete(F arg0, Object params) throws java.lang.Exception;
}
```

**Comment by ylgrgyq** [comment] 2016-03-24 23:38
I think maybe it's because you don't wait all sendNotificationAsync finish. 
Why not add a CountDownLatch and countDown it in sendNotificationFuture's listener. In this way you can count every response from apns and wait this latch down to 0. At that time you can quit the test safely.

**Comment by manusdiaz** [comment] 2016-03-25 10:16
Thank you very much for your attention!
Really I have a counter and I wait 30 seconds before finishing the test. I've collected traces:

Test 1. 10 notifications with async send and wait 30 seconds (timeout) before finishing the test. Traces: 
9 Success --> I only see the last success. Success or error 0 to 8 missing.
After 30 seconds of test:

Counter tentative: 10
Counter success: 1
Counter failure: 0

If I wait 1 second before sending a notification in for loop I see 0 to 9 success.

¿Is it possible that sendNotificationFuture..addListener(new ListenerWrapper... override the last listener and lose references to other listeners?  I always use the same instance of ApnsClient, but I create a new Listener for each future returned by sendNotification.

**Comment by jchambers** [comment] 2016-03-25 14:18
I added a unit test to make sure listeners are working in 0af8295. The test does pass, so I don't think we're dealing with a bug in Pushy.

That said, I tried to build your code and had a little trouble (looks like there are a few bonus `}` characters floating around). Reading through it, though, I can't help but notice that you're not waiting for the connection attempt to complete before you start sending notifications. What happens if you change this:

```java
Future<Void> connectFuture = apnsClient.connect(ApnsClient.DEVELOPMENT_APNS_HOST);
```

…to this?

```java
Future<Void> connectFuture = apnsClient.connect(ApnsClient.DEVELOPMENT_APNS_HOST);
connectFuture.await();
```

Also, you've wrapped the `sendNotification` call in a `try/catch` block, and you only increment your failure counter if you catch an exception there. Please note that `sendNotification` doesn't actually throw exceptions (so I'd never expect that `catch` block to fire); if something goes wrong, the `Future` returned by `sendNotification` will return `false` from `isSuccess`, and `future.cause()` will return the exception that caused the failure. I think if you move `counter.addFailure();` into the future listener, you might find your missing failures (which, again, I suspect are caused by trying to send notifications before the connection is established).

Hope that helps!

Since this doesn't appear to be a bug in Pushy, I'm going to close this issue (but will happily re-open it if we discover that something else is going wrong).

**Comment by jchambers** [comment] 2016-03-26 01:59
…and where are my manners?

We would, of course, be happy to help you with things that aren't bugs on the [mailing list](https://groups.google.com/d/forum/pushy-apns). Please give a shout there if you're still having trouble!

**Comment by manusdiaz** [comment] 2016-03-27 15:10
I got it! You have helped me a lot. The problem wasn't the connection. I didn't give you the complete code to simplify the problem (sorry), but I was waiting for the connection. The problem is to try to send the same push notification. Let me explain. In your code, you first create each notification, then insert it in a list and then send every notification, like this (your test code):

for (int i = 0; i < notificationCount; i++) {  
             final String token = ApnsClientTest.generateRandomToken();  
             final String payload = ApnsClientTest.generateRandomPayload();  
   
             this.server.registerToken(DEFAULT_TOPIC, token);  
             pushNotifications.add(new SimpleApnsPushNotification(token, DEFAULT_TOPIC, payload));  
         }  
   
         final CountDownLatch countDownLatch = new CountDownLatch(notificationCount);  
  
         for (final SimpleApnsPushNotification pushNotification : pushNotifications) {  
             final Future<PushNotificationResponse<SimpleApnsPushNotification>> future =  
331 +                     this.client.sendNotification(pushNotification);  

If you change the line 331, and use pushNotifications.get(0) instead of pushNotification, to send always the same notification , you'll be able to see the same problem I had. With my code, if I create a different notification before sending, I have the expected beahaviour (only a logical too many request in development environment).

I think this is not a bug, because it's correct to create a different notification before sending, but it would be very interesting to understand why happen this (only curiosity :) ).

Thanks once again for your attention.

**Comment by jchambers** [comment] 2016-03-27 18:07
Ah—I see. Yeah, that's because of this (from `ApnsClient`):

```java
private final Map<T, Promise<PushNotificationResponse<T>>> responsePromises = new IdentityHashMap<>();
```

When we send a notification we create a `Promise` so we can notify interested parties that the operation is complete. If we're using *literally the same* notification all the time, callers may think they've sent a thousand notifications, but that map will only contain one entry.

I'm… not really sure what to think about that. On one hand, this doesn't reeeeeeeally seem like a case where we want to build a whole lot of machinery to protect against this problem. On the other hand, it seems weird that callers could cause a bunch of internal exceptions by passing what *looks like* reasonable, legal input.

I guess we could check to see if notifications are already in the map before we send them. What do you think? Is it worth it?

**Comment by manusdiaz** [comment] 2016-03-27 19:14
From my point of view, the implementation must be responsible for detecting problems with inputs and reporting problems correctly. I would assume this like a minor bug, visible for other people. Probably, with a check in sendNotification method and a exception with the rejected information, could be enough.

We're working in a communication platform for 4 million of customers and we must change our old Apple push connector, because our old one has a lot of problems. Tomorrow we start with this development and we would be delighted to give you feedback. ¿Which would be the correct channel (email, mailing lists,...) for particular questions or good practices? (of course after reading documentation, reviewed mailing lists, etc.).

**Comment by jchambers** [comment] 2016-03-27 19:53
> From my point of view, the implementation must be responsible for detecting problems with inputs and reporting problems correctly.

Yeah—I can get behind that. Reopening, reclassifying, and assigning this to v0.6.

> Which would be the correct channel (email, mailing lists,...) for particular questions or good practices?

Probably the mailing list.

Looking forward to hearing how your integration goes! Please don't be shy with the feedback.

**Comment by jchambers** [comment] 2016-03-27 20:33
Resolved the underlying issue by checking for map membership when sending notifications.

**Closed** 2016-03-27 20:33 UTC
Labels: bug
