### ISSUE TITLE
ApnsClient::close causes UDP port leak if EventLoopGroup is provided to ApnsClient ctor - 0.13.5

### ISSUE THREAD

**Issue by eugeneseppel** [relayrides/pushy#692] opened 2019-04-16 08:20 UTC
The following code causes UDP port leak. Every new iteration opens UDP port and doesn't close it. This appears only with new versions of Pushy (after 0.13)
```
final ApnsSigningKey signingKey = ApnsSigningKey.loadFromPkcs8File(SIGNING_KEY_FILE, TEAM_ID, KEY_UD);
final SimpleApnsPushNotification pushNotification = new SimpleApnsPushNotification(TOKEN, TOPIC, "{}");

while (true) {
    final ApnsClient client = new ApnsClientBuilder()
            .setApnsServer(ApnsClientBuilder.DEVELOPMENT_APNS_HOST)
            .setSigningKey(signingKey)
            .setEventLoopGroup(new NioEventLoopGroup(1))
            .build();

    client.sendNotification(pushNotification).await();
    client.close().await();

    Thread.sleep(1000);
}
```
This issue appeared after introducing RoundRobinDnsAddressResolverGroup in ApnsChannelFactory:: this.bootstrapTemplate.resolver 
See #675 and #632

**Comment by jchambers** [comment] 2019-04-16 17:18
This is a duplicate of #675. Let's close this issue and keep the conversation in one place.

**Closed by jchambers** 2019-04-16 17:18 UTC
